app_home:
  path: /
  controller: App\Controller\HomeController::index

app_login:
  path: /login
  controller: App\Controller\UserController::login

app_register:
  path: /register
  controller: App\Controller\UserController::register

app_logout:
  path: /logout

app_figure:
  path: /figure/new
  controller: App\Controller\FigureController::new
