app_home:
  path: /home
  controller: App\Controller\HomeController::index

app_login:
  path: /login
  controller: App\Controller\UserController::login

app_register:
  path: /register
  controller: App\Controller\UserController::register

app_logout:
  path: /logout

app_activate:
  path: /activate/{token}
  controller: App\Controller\UserController::activate

app_forgot_password:
  path: /forgot-password
  controller: App\Controller\UserController::forgotPassword

app_reset_password:
  path: /reset-password/{token}
  controller: App\Controller\UserController::resetPassword

app_figure:
  path: /figure/new
  controller: App\Controller\FigureController::new
